version: '3.9'

services:
  processing_service:
    build: processing_service
    volumes:
      - ./processing_service:/usr/src/processing_service
    ports:
      - 7779:8000
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/processing_service/uvicorn_logging.conf"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]