version: '3.9'

services:
  postgres:
    image: postgres:16.1-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_CONTAINER_PORT}:5432
  backend:
    build: backend
    volumes:
      - ./backend:/usr/src/backend
    env_file:
      - ./backend/.env
    ports:
      - 7778:8000
    depends_on:
      - postgres
    command: >
      sh -c "alembic upgrade head && 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/backend/uvicorn_logging.conf"

volumes:
  postgres_data:
