"""Ticket

Revision ID: 9540acf05713
Revises: 26f130f7f14e
Create Date: 2024-03-27 16:39:40.647401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9540acf05713'
down_revision: Union[str, None] = '26f130f7f14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(length=64), nullable=True))
    op.add_column('tickets', sa.Column('completion_image', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('completion_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'completion_timestamp')
    op.drop_column('tickets', 'completion_image')
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
