"""Contractors

Revision ID: 961423fbad0a
Revises: 7c160c35dea8
Create Date: 2024-03-28 03:51:14.934846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961423fbad0a'
down_revision: Union[str, None] = '7c160c35dea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('tickets', sa.Column('contractor_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('completion_target_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'contractors', ['contractor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'completion_target_date')
    op.drop_column('tickets', 'contractor_id')
    op.drop_table('contractors')
    # ### end Alembic commands ###
