"""2 images

Revision ID: e25009cd0e54
Revises: 961423fbad0a
Create Date: 2024-03-28 05:40:53.089902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25009cd0e54'
down_revision: Union[str, None] = '961423fbad0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('original_image', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('processed_image', sa.Text(), nullable=True))
    op.drop_column('tickets', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'processed_image')
    op.drop_column('tickets', 'original_image')
    # ### end Alembic commands ###
